version: '2.1'
services:
  web:
    image: nginx
    restart: always
    depends_on:
      - php
    ports:
      - 8080:80
    volumes:
      - ./web/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    env_file: .env
  php:
    build: ./php
    restart: always
    depends_on:
      - db
    volumes:
      - ./htdocs:/var/www/html
      - ./php/conf.d/custom-php.ini:/usr/local/etc/php/conf.d/zz-custom.ini
      - ./php/.bashrc:/root/.bashrc
    env_file: .env
  db:
    image: mariadb
    restart: always
    volumes:
      - ./db/conf.d/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./db/data:/var/lib/mysql
    env_file: .env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8282:80
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    env_file: .env
