version: '2.1'
services:
  nginx:
    image: nginx
    restart: always
    depends_on:
      - php
    ports:
      - 8080:80
    volumes:
      - ./services/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    env_file: .env
  php:
    build: ./services/php
    restart: always
    depends_on:
      - mariadb
    volumes:
      - ./htdocs:/var/www/html
      - ./services/php/conf.d/custom-php.ini:/usr/local/etc/php/conf.d/zz-custom.ini
      - ./services/php/.bashrc:/root/.bashrc
    env_file: .env
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./services/mariadb/conf.d/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./services/mariadb/data:/var/lib/mysql
    env_file: .env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8282:80
    volumes:
      - ./services/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    env_file: .env
